#!/bin/bash

clear
if [[ -z "$@" ]]
then
	echo -n "Enter commands: "
	read CMD
	while true
	do
		NUM=$(($NUM+1))
		echo -e "RUN $NUM\n"
		$CMD
		sleep 1
		clear
	done
else
	while true
        do
                NUM=$(($NUM+1))
                echo -e "RUN $NUM\n"
                $@
                sleep 1
                clear
        done
fi

